--------------------------------------------------------
--  File created - Wednesday-June-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "SYS"."COUNTRIES" 
   (	"ID" NUMBER(*,0), 
	"COUNTRY_NAME" VARCHAR2(100 BYTE), 
	"SLUG" VARCHAR2(100 BYTE), 
	"ISO2" VARCHAR2(20 BYTE), 
	"LOCATION_AT" VARCHAR2(20 BYTE), 
	"LOCATION_ON" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COUNTRIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."COUNTRIES_PK" ON "SYS"."COUNTRIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "SYS"."COUNTRIES" MODIFY ("SLUG" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COUNTRIES" MODIFY ("ISO2" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COUNTRIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COUNTRIES" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COUNTRIES" ADD CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
