--------------------------------------------------------
--  File created - Wednesday-June-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GLOBALS
--------------------------------------------------------

  CREATE TABLE "SYS"."GLOBALS" 
   (	"CONFIRMED" NUMBER(*,0), 
	"DEATHS" NUMBER(*,0), 
	"RECOVERED" NUMBER(*,0), 
	"ACTIVE" NUMBER(*,0), 
	"DATE_DAY" NUMBER(*,0), 
	"DATE_MONTH" NUMBER(*,0), 
	"DATE_YEAR" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GLOBALS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."GLOBALS_PK" ON "SYS"."GLOBALS" ("DATE_YEAR", "DATE_MONTH", "DATE_DAY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GLOBALS
--------------------------------------------------------

  ALTER TABLE "SYS"."GLOBALS" MODIFY ("CONFIRMED" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GLOBALS" MODIFY ("DATE_DAY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GLOBALS" MODIFY ("DATE_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GLOBALS" MODIFY ("DATE_YEAR" NOT NULL ENABLE);
  ALTER TABLE "SYS"."GLOBALS" ADD CONSTRAINT "GLOBALS_PK" PRIMARY KEY ("DATE_YEAR", "DATE_MONTH", "DATE_DAY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
