CREATE OR REPLACE PROCEDURE SP_INSERT_COVID_COUNTRIES
    (CT_ID in number,CFM in number,DEATHS in NUMBER,RECOVERED IN NUMBER,ACTIVE IN NUMBER,
        DATE_TIME IN DATE)
AS
BEGIN
    INSERT INTO COVID_COUNTRIES(country_id,confirmed,deaths,recoverd,active,date_time,date_year,date_month,date_day) VALUES
    (CT_ID,CFM,DEATHS,RECOVERED,ACTIVE,
    DATE_TIME,TO_CHAR(DATE_TIME,'YYYY'),TO_CHAR(DATE_TIME,'MM'),TO_CHAR(DATE_TIME,'DD'));
END SP_INSERT_COVID_COUNTRIES;

EXEC SP_INSERT_COVID_COUNTRIES (111,0,0,0,0,TO_DATE('05-11-2020 12:00:00','DD-MM-YYYY HH24:MI:SS'));

SELECT * FROM covid_countries WHERE id = 111;